'use client'
import './globals.css'
import '../styles/index.css'
import '../styles/bootstrap.min.css'

// import type { Metadata } from 'next'
import { Container } from 'react-bootstrap'
import { Provider } from 'react-redux'
import { Inter } from 'next/font/google'
import { useStore } from '@/state'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const initialState = {
    // ...pageProps.initialReduxState,
  }

  const store = useStore(initialState)

  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <Container>{children}</Container>
        </body>
      </html>
    </Provider>
  )
}
